spring.application.name=SpringBoot2Project
server.port=8060
    
    # logging level 설정
logging.level.kr.or.ddit=info
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
logging.level.p6spy=debug

# 폼 파일 업로드 용량제한 설정
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=20MB
server.tomcat.max-part-count=30

# 파일 업로드 저장 (물리)경로 설정 및 환경변수(UPLOAD_PATH) 주입. (주의! 공백있으면 안됨)
# (UPLOAD_PATH라는 환경변수가 존재하면 그것으로 설정 없다면 C:/upload/로 설정
kr.or.ddit.upload.path=${UPLOAD_PATH:C:/upload}

# 데이터베이스 접속 정보 설정(datasource)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=boot
spring.datasource.password=java
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.type-aliases-package=kr.or.ddit.vo
mybatis.mapper-locations=classpath:mybatis/mapper/*_Mapper.xml

